### PR TITLE
Repoless ops

### PR DESCRIPTION
**Pull request by worr**
Currently, users need to call repo :repo to run pretty much every operation.

With this patch, users who logged in can instead call functions like r.list without having to set a repo first. This makes the application significantly easier to use, imo.

### CODE REVIEW

**Comment by fayland** [comment]
Hi, do you have a CPAN id? I'd like to pass the maintainshipper to you if you want.

Thanks

**Comment by worr** [comment]
Sure, it's the same as my github username. I don't particularly care either way about maintaining it, mostly I just wanted to use it, and I was encountering bugs/non-features. I have more patches on the way, if you want to keep your hands on it.

**Comment by fayland** [comment]
OK, just do it as you want. or else, I'll take care of it.

Added WORR to co-maintainers of App::GitHub.

Thanks.

**Comment by worr** [comment]
Am I a co-maintainer? I can't find this anywhere.

For now, I'll just continue to submit pull requests.

**Comment by fayland** [comment]
you can check here: https://pause.perl.org/pause/authenquery?ACTION=peek_perms

and feel free to upload a new version.

Thanks

**Comment by worr** [comment]
Awesome, thanks!

Do you want this repo to stay official? Or should I use mine as the official repo?

**Comment by fayland** [comment]
yours is fine. :)

Thanks

**Pull request merged**
